/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    _: typeof import('./src/components/Chat/_.vue')['default']
    AButton: typeof import('ant-design-vue/es')['Button']
    AppSidebar: typeof import('./src/components/Sidebar/AppSidebar.vue')['default']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    ChatInput: typeof import('./src/components/Chat/ChatInput.vue')['default']
    ChatList: typeof import('./src/components/Sidebar/ChatList.vue')['default']
    MessageList: typeof import('./src/components/Chat/MessageList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Settings: typeof import('./src/components/Sidebar/Settings.vue')['default']
  }
}
